// Cadrul cabinetului: ecranul de eroare de configurare, antetul, navigatia
// intre sectiuni si formularul de autentificare din AdminApp.tsx.
export const app = {
  en: {
    'app.not_connected_title': 'Admin is not connected yet',
    'app.not_connected_body':
      'Supabase environment variables are missing. Add PUBLIC_SUPABASE_URL and PUBLIC_SUPABASE_ANON_KEY, then redeploy. See docs/SETUP-RO.md in the project.',
    'app.loading': 'Loading...',
    'app.brand': 'Essential Flooring',
    'app.subtitle': 'Admin cabinet',
    'app.view_site': 'View website',
    'app.sign_out': 'Sign out',
    'app.nav_label': 'Admin sections',
    'app.tab_dashboard': 'Traffic',
    'app.tab_leads': 'Leads',
    'app.tab_portfolio': 'Portfolio',
    'app.tab_reviews': 'Reviews',
    'app.tab_blog': 'Blog',
    'app.tab_seo': 'SEO',
    'app.menu': 'Menu',
    'app.close': 'Close',
    'app.lang_label': 'Language',
    'app.email_label': 'Email',
    'app.password_label': 'Password',
    'app.login_error': 'Wrong email or password.',
    'app.signing_in': 'Signing in...',
    'app.sign_in': 'Sign in',
  },
  ro: {
    'app.not_connected_title': 'Cabinetul nu este conectat încă',
    'app.not_connected_body':
      'Lipsesc variabilele de mediu Supabase. Adaugă PUBLIC_SUPABASE_URL și PUBLIC_SUPABASE_ANON_KEY, apoi publică site-ul din nou. Vezi docs/SETUP-RO.md în proiect.',
    'app.loading': 'Se încarcă...',
    'app.brand': 'Essential Flooring',
    'app.subtitle': 'Cabinet de administrare',
    'app.view_site': 'Vezi site-ul',
    'app.sign_out': 'Ieși din cont',
    'app.nav_label': 'Secțiunile cabinetului',
    'app.tab_dashboard': 'Trafic',
    'app.tab_leads': 'Cereri',
    'app.tab_portfolio': 'Portofoliu',
    'app.tab_reviews': 'Recenzii',
    'app.tab_blog': 'Blog',
    'app.tab_seo': 'SEO',
    'app.menu': 'Meniu',
    'app.close': 'Închide',
    'app.lang_label': 'Limbă',
    'app.email_label': 'Email',
    'app.password_label': 'Parolă',
    'app.login_error': 'Email sau parolă greșite.',
    'app.signing_in': 'Se conectează...',
    'app.sign_in': 'Intră în cont',
  },
} as const;
